- name: installing docker package
  package: 
      name: docker
      state: present

- name: creating k8s yum file 
  copy:
      dest: /etc/yum.repos.d/kubernetes.repo
      content: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: creating k8s conf file and enabling bridge setting 
  copy:
      dest: /etc/sysctl.d/k8s.conf
      content: |
              net.bridge.bridge-nf-call-ip6tables = 1
              net.bridge.bridge-nf-call-iptables = 1


- name: installing kubelet kubeadm kubectl 
  package: 
      name: 
      - kubelet 
      - kubeadm 
      - kubectl
      state: present

- name: starting kubelet service
  service:
      name: kubelet
      state: started
      enabled: yes 

- name: changing cgroupdriver to systemd
  copy:
      dest: /etc/docker/daemon.json
      content: |
             {
                "exec-opts": ["native.cgroupdriver=systemd"]
             }

- name: starting docker services 
  service:
      name: docker 
      state: started
      enabled: yes

- name: installing iproute-tc
  package:
      name: iproute-tc
      state: present

- name: setting up iptables and reloading kernal
  sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      sysctl_set: yes
      state: present
      reload: yes 
  
- block:
    - name: copying the tokenfile to nodes
      copy:
        src: tokenfile
        dest: /home/ec2-user/tokenfile
        mode: 0775
      register: copied

    - name: connection establishing
      shell: $PWD/tokenfile
      when: copied.changed==true
   
  rescue: 
    - debug: 
        msg: master unreachable
